[server]
address = "0.0.0.0:8000"
workers = 1
max_content_length = "50MB"
upload_path = "/data/uploads"
timeout = "15s"
expose_list = true

[server.auth]
tokens = ["__AUTH_TOKEN__"]
delete_tokens = ["__DELETE_TOKEN__"]

[landing_page]
file = "/config/landing_page.html"
content_type = "text/html; charset=utf-8"

[paste]
random_url = { type = "alphanumeric", length = 6 }
duplicate_files = true
default_extension = "txt"
delete_expired_files = { enabled = true, interval = "4h" }
