server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 2s
    batchsize: 1048576

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: lepotato
          __path__: /var/log/**/*.log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - regex:
          expression: '.*level(?:=|:)?(?P<level>\\w+).*'
      - drop:
          source: level
          expression: '(?i)debug|trace'

  - job_name: kopia
    static_configs:
      - targets:
          - localhost
        labels:
          job: kopia
          host: lepotato
          __path__: /kopia-logs/*.log

  - job_name: qbittorrent
    static_configs:
      - targets:
          - localhost
        labels:
          job: qbittorrent
          host: lepotato
          __path__: /qbittorrent-logs/*.log

  - job_name: slskd
    static_configs:
      - targets:
          - localhost
        labels:
          job: slskd
          host: lepotato
          __path__: /slskd-logs/*.log

  - job_name: netdata
    static_configs:
      - targets:
          - localhost
        labels:
          job: netdata
          host: lepotato
          __path__: /netdata-logs/*.log
