---
apiVersion: v1
kind: Namespace
metadata:
  name: potatostack
  labels:
    name: potatostack
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: potatostack-monitoring
  labels:
    name: potatostack-monitoring
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: potatostack-vpn
  labels:
    name: potatostack-vpn
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: potatostack-operators
  labels:
    name: potatostack-operators
