---
- VPN & Downloads:
    - Gluetun VPN:
        icon: gluetun.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8000
        description: VPN Killswitch
        server: docker-socket
        container: gluetun
        widget:
          type: gluetun
          url: http://gluetun:8000

    - Transmission:
        icon: transmission.png
        href: http://{{HOMEPAGE_VAR_HOST}}:9091
        description: Torrent Client (via VPN)
        server: docker-socket
        container: transmission
        widget:
          type: transmission
          url: http://gluetun:9091
          username: {{HOMEPAGE_VAR_TRANSMISSION_USER}}
          password: {{HOMEPAGE_VAR_TRANSMISSION_PASS}}
          rpcUrl: /transmission/

    - slskd:
        icon: slskd.png
        href: http://{{HOMEPAGE_VAR_HOST}}:2234
        description: Soulseek Client (via VPN)
        server: docker-socket
        container: slskd
        widget:
          type: slskd
          url: http://gluetun:2234
          apikey: {{HOMEPAGE_VAR_SLSKD_KEY}}

- Media & Storage:
    - Immich:
        icon: immich.png
        href: http://{{HOMEPAGE_VAR_HOST}}:2283
        description: Photo Management
        server: docker-socket
        container: immich-server
        widget:
          type: immich
          url: http://immich-server:3001
          key: {{HOMEPAGE_VAR_IMMICH_KEY}}

    - Syncthing:
        icon: syncthing.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8384
        description: P2P File Sync
        server: docker-socket
        container: syncthing
        widget:
          type: syncthing
          url: http://syncthing:8384

    - Kopia:
        icon: kopia.png
        href: https://{{HOMEPAGE_VAR_HOST}}:51515
        description: Backup Server
        server: docker-socket
        container: kopia
        widget:
          type: kopia
          url: https://kopia:51515
          username: {{HOMEPAGE_VAR_KOPIA_USER}}
          password: {{HOMEPAGE_VAR_KOPIA_PASS}}

- Security & Management:
    - Vaultwarden:
        icon: vaultwarden.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8080
        description: Password Manager
        server: docker-socket
        container: vaultwarden
        widget:
          type: vaultwarden
          url: http://vaultwarden:80

    - Portainer:
        icon: portainer.png
        href: https://{{HOMEPAGE_VAR_HOST}}:9443
        description: Container Management
        server: docker-socket
        container: portainer
        widget:
          type: portainer
          url: https://portainer:9443
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

- System & Monitoring:
    - PostgreSQL:
        icon: postgres.png
        href: '#'
        description: Shared Database
        server: docker-socket
        container: postgres
        widget:
          type: postgres
          url: postgres://postgres:5432
          username: postgres
          password: {{HOMEPAGE_VAR_POSTGRES_PASS}}

    - Redis:
        icon: redis.png
        href: '#'
        description: Shared Cache
        server: docker-socket
        container: redis
        widget:
          type: redis
          url: redis://redis:6379

    - FritzBox:
        icon: avm-fritzbox.png
        href: http://fritz.box
        description: Router Metrics
        server: docker-socket
        container: fritzbox-exporter
