apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: potatostack
data:
  configuration.yml: |
    server:
      host: 0.0.0.0
      port: 9091

    log:
      level: info

    theme: auto

    totp:
      issuer: authelia.lepotato.local
      period: 30
      skew: 1

    authentication_backend:
      file:
        path: /config/users_database.yml

    access_control:
      default_policy: deny
      rules:
        - domain: "*.lepotato.local"
          policy: one_factor

    session:
      name: authelia_session
      domain: lepotato.local
      expiration: 1h
      inactivity: 5m
      redis:
        host: redis.potatostack.svc.cluster.local
        port: 6379
        database_index: 1

    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m

    storage:
      local:
        path: /var/lib/authelia/db.sqlite3

    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        username: ${AUTHELIA_NOTIFIER_SMTP_USERNAME}
        password: ${AUTHELIA_NOTIFIER_SMTP_PASSWORD}
        sender: authelia@lepotato.local

  users_database.yml: |
    users:
      admin:
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$REPLACEME"
        email: admin@lepotato.local
        groups:
          - admins

