# Netdata (official chart)

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - netdata.lepotato.local

parent:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  database:
    persistence: true
    volumesize: 2Gi
  alarms:
    persistence: true
    volumesize: 512Mi

child:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
