apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmaps
  - ./deployments
  - ./ingress
  - ./namespaces
  - ./networkpolicies
  - ./operators
  - ./pvc
  - ./secrets
  - ./services
  - ./statefulsets
  - ./monitoring
  - ./ingress-nginx
  - ../apps