apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielfriedrich-xyz/vllm-windows.git
    targetRevision: HEAD
    path: k8s/base
    directory:
      exclude: '{monitoring,operators}'
  destination:
    server: https://kubernetes.default.svc
    namespace: potatostack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
