pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://ciechanow.ski/atom.xml
                title: Bartosz Ciechanowski
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
                title: Sam Who
              - url: https://awesomekling.github.io/feed.xml
                title: Andreas Kling

          - type: twitch-channels
            channels:
              - theprimeagen
              - cohhcarnage
              - christitustech

      - size: full
        widgets:
          - type: hacker-news

          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips

      - size: small
        widgets:
          - type: weather
            location: Berlin, Germany

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: http://192.168.178.158:8096
                icon: si:jellyfin
              - title: Vaultwarden
                url: http://192.168.178.158:8888
                icon: si:bitwarden
              - title: Grafana
                url: http://192.168.178.158:3000
                icon: si:grafana
