use_default_settings: true

general:
  instance_name: "PotatoStack Search"
  privacypolicy_url: false
  donation_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 2
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  base_url: "https://potatostack.tale-iwato.ts.net:8180/"
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: true
  image_proxy: true
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: redis://redis-cache:6379/15

ui:
  static_use_hash: true
  default_theme: simple
  center_alignment: true
  query_in_title: true
  infinite_scroll: true
  theme_args:
    simple_style: dark

outgoing:
  request_timeout: 6.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 15
  enable_http2: true

enabled_plugins:
  - Hash plugin
  - Self Information
  - Tracker URL remover
  - Unit converter
  - Hostnames plugin
  - Open Access DOI rewrite
