use_default_settings: true

general:
  instance_name: "PotatoStack Search"
  privacypolicy_url: false
  donation_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 2
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  secret_key: "${SEARXNG_SECRET}"
  limiter: true
  image_proxy: true
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: redis://redis-cache:6379/15

cache:
  cache_dir: ""
  cache_type: redis

ui:
  static_use_hash: true
  default_theme: simple
  center_alignment: true
  query_in_title: true
  infinite_scroll: true
  theme_args:
    simple_style: dark

outgoing:
  request_timeout: 6.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 15
  enable_http2: true

enabled_plugins:
  - Hash plugin
  - Self Information
  - Tracker URL remover
  - Unit converter
  - Hostnames plugin
  - Open Access DOI rewrite
  - Tor check plugin

engines:
  - name: google
    engine: google
    shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: bing
    engine: bing
    shortcut: b

  - name: brave
    engine: brave
    shortcut: br

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: wikidata
    engine: wikidata
    shortcut: wd

  - name: github
    engine: github
    shortcut: gh

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so

  - name: arch wiki
    engine: archlinux
    shortcut: aw

  - name: reddit
    engine: reddit
    shortcut: r

  - name: npm
    engine: npm
    shortcut: npm

  - name: pypi
    engine: pypi
    shortcut: pip

  - name: dockerhub
    engine: docker_hub
    shortcut: dh

  - name: crates.io
    engine: crates
    shortcut: cra
